import { ReactNode } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import Header from "@/components/layout/Header";
import SearchBar from "@/components/layout/SearchBar";
import styles from "@/styles/layout/Layout.module.css";

interface LayoutProps {
  children?: ReactNode;
}

export default function Layout({ children }: LayoutProps): JSX.Element {
  const router = useRouter();

  function handleSearch(value: string) {
    if (!value) {
      router.push("/");
    } else {
      router.push(`/search?q=${encodeURIComponent(value)}`);
    }
  }

  return (
    <>
      <Head>
        <title>GIPHY Search</title>
        <meta name="description" content="Generated by Bannon Tanner" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.headersearch}>
          <Header />
          <SearchBar onSearch={handleSearch} />
        </div>
        <div className={styles.gifs}>{children}</div>
      </main>
    </>
  );
}
