import { ReactNode } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Layout.module.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
  children?: ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>GIPHY Search</title>
        <meta name="description" content="Generated by Bannon Tanner" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header />
        {/* Search */}
        {children}
      </main>
    </>
  );
}
